### ISSUE TITLE
Failed to minify the code with webpack

### ISSUE THREAD

**Issue by yingapp** [joshuaquek/QuickEncrypt#16]
package.json
    "webpack": "3.8.1",

Failed to minify the code from this file:

        ./node_modules/quick-encrypt/index.js:4

Read more here: http://bit.ly/2tRViJ9

**Comment by joshuaquek** [comment]
It seems that you are trying to compile this in a ReactJS project.

Following your link provided above, it finally lead me to this page: 
https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify

For your project, you can follow the solution provided in that link.
